export class CreateOrderRersponse {
    activeStandingOrder: boolean;
    address: string;
    bankAccount: string;
    cardExpiryMonth: number
    cardExpiryYear: number
    cardNumber: string
    cardStatus: string
    cardStatusDate: any
    checkDigit: number
    city: string
    customerStatus: string
    customerStatusDate: any
    email: string
    endDate: any
    endorsement: string
    firstName: string
    iban: string
    id: number
    lastName: number
    lineOfBusiness: string
    newCollectionAgency: number
    oldCollectionAgency: number
    organizationDescription: string
    paymentType: string
    phone: number
    policyNo: number
    policyStatus: string
    policyStatusDate: any
    postalCode: string
    recordStatus: string
    recordStatusDate: any
    standingOrderStatus: string
    standingOrderStatusDate: any
    startDate: any
    vatNumber: string
    versionNo: number
}